[package]
name = "andromeda-socket-osmosis"
version = "0.1.0-b.1"
edition = "2021"
rust-version = "1.75.0"


exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
testing = ["cw-multi-test", "andromeda-testing"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
schemars = "0.8.16"
serde = { workspace = true }
thiserror = { workspace = true }
cw-utils = { workspace = true }
andromeda-std = { workspace = true }
cw20 = "1.1.2"
andromeda-socket = { workspace = true }
osmosis-std = "0.27.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { workspace = true, optional = true }
cw-orch = { workspace = true }
andromeda-testing = { workspace = true, optional = true }
cw-orch-daemon = "0.24.2"
