[package]
name = "andromeda-accounts"
version = "1.0.0"
edition = "2018"
rust-version = "1.75.0"
description = "Utility methods and message definitions for the Andromeda Accounts Contracts"
license = "MIT"

[features]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw3 = { workspace = true }
cw-utils = { workspace = true }

andromeda-std = { workspace = true, features = [] }
